### ISSUE TITLE
Subscribe to events?

### ISSUE THREAD

**Issue by jake2184** [ibm-watson-iot/iot-starter-for-android#1]
Can the Android setup here be used to subscribe to an event from another device? Or is there a way to change it from being a 'device' into an 'application' so it can subscribe to events?

**Comment by robert17** [comment]
The app was only written to act as a single device that can send its own events and receive its own commands.

If you want to use it as an application you would need to:
1. Take API key and token as input rather than device ID and device auth token
2. Update the MQTT client id used from d:<org>:<deviceType>:<deviceId> to a:<org>:<app id>
3. Update MQTT username from use-token-auth to the API Key
4. Update MQTT password from device auth token to API Token
5. Update subscribed topics to match API key format: iot-2/type/<type>/id/<id>/evt/<event>/fmt/<format> and similar for commands if you are using those as well.

**Comment by jake2184** [comment]
Thank you for the comprehensive TODO list, I'll try it during this week. 
.

**Comment by jake2184** [comment]
Works brilliantly, thank you.
