### ISSUE TITLE
Client certificate support

### ISSUE THREAD

**Issue by SebastianSingle99** [ibm-watson-iot/iot-starter-for-android#6]
Is there an example how to use a client certificate to connect to an iot-mqtt server?
I'm currently using paho for android and have a valid client certificate from watson-iot.
The server complains about an **Invalid userID**. 
The client-id is like this
` d:orgId:devclassID:devUUID`

The example in this lib or in the java-iot repo only use token-based authentication.
Do i have to set something else for
` username="use-token-auth"`?

**Comment by robert17** [comment]
A little late, but if you're still interested in an answer to this:

In order to use client certificates to authenticate a device you must have an IoT service created with the Advanced Security Plan (ASP).

With an ASP organization, you can configure the connection security policy to be `TLS with Client Certificate Authentication`.

Assuming you have a CA certificate which can be used to sign certificates, you can upload this CA public certificate to your organizations CA certificates.

More information is available in the documentation [here](https://console.bluemix.net/docs/services/IoT/reference/security/set_up_certificates.html#set_up_certificates).

To create a certificate for your device, you could do something like:

```
cat > srvext.cfg <<EOF
[ req ]
req_extensions          = v3_req
[ v3_req ]
subjectAltName          = email:d:{{DEVICE_TYPE}}:{{DEVICE_ID}}
EOF

openssl genrsa -out dev-key.pem 4096 >/dev/null 2>/dev/null
openssl req -new -days 1800 -subj "/C=US/ST=Texas/L=Austin/O=IBM/OU=IOT/CN=d:{{DEVICE_TYPE}}:{{DEVICE_ID}}" -key dev-key.pem -out devcert.csr
openssl x509 -days 1800 -in devcert.csr -out dev-crt.pem -req -CA {{CA_CERT}} -CAkey {{CA_KEY}} -extensions v3_req -extfile srvext.cfg -set_serial 1 2>/dev/null

openssl pkcs12 -export -inkey dev-key.pem -in dev-crt.pem -out devcert.p12 -password pass:passw0rd
keytool -importkeystore -srckeystore devcert.p12 -destkeystore devcert.jks -srcstoretype pkcs12 -deststorepass passw0rd -deststoretype jks -srcstorepass passw0rd
```

Where:
- DEVICE_TYPE is your IoT device type
- DEVICE_ID is your IoT device id
- CA_CERT is the public certificate of your signing CA
- CA_KEY is the private key of your signing CA

This will result in a `devcert.jks` containing the device certificate/key pair which can be used for client certificate authentication with your IoT service.

In order to use this with the Eclipse Paho java client, you will need to be using the latest 1.1.1-SNAPSHOT version.

The following snippet shows how you could use the client certificate keystore:

```
	public static void main(String [] args) {

		MqttClient client = null;
		MqttConnectOptions connOpts = null;

		try {
			System.getProperties().put("javax.net.ssl.keyStore", "/Users/wiotp-dev/workspace/client-cert-sample/resources/devcert.jks");
			System.getProperties().put("javax.net.ssl.keyStorePassword", "passw0rd");
			System.getProperties().put("javax.net.ssl.trustStore", "/Users/wiotp-dev/workspace/client-cert-sample/resources/public-messaging-wiotp.jks");
			System.getProperties().put("javax.net.ssl.trustStorePassword", "passw0rd");

			MqttConnectOptions connOpts = new MqttConnectOptions();
			connOpts.setCleanSession(true);
			// connOpts.setUserName("use-token-auth");
			// connOpts.setPassword("passw0rd".toCharArray());

			String brokerURL = "ssl://" + ORG_ID + .messaging.internetofthings.ibmcloud.com:8883";
			String clientID = "d:" + ORG_ID + ":" + DEVICE_TYPE + ":" + DEVICE_ID;

			client = new MqttClient(brokerURL, clientID);
			client.connect(connOpts);

			// ...

			client.disconnect();
		} catch (MqttException e) {
			e.printStackTrace();
		}
	}
```

The above snippet is for the regular java client library but something similar could probably be used within the Android application. The JKS would need to be recreated as a BKS instead (BouncyCastle keystore).

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
